[
  { "script_text": "All that glitters is not gold",
    "script_tone": {"tone_categories":[{"tones":[{"score":0.328683,"tone_id":"anger","tone_name":"Anger"},{"score":0.160157,"tone_id":"disgust","tone_name":"Disgust"},{"score":0.285003,"tone_id":"fear","tone_name":"Fear"},{"score":0.062344,"tone_id":"joy","tone_name":"Joy"},{"score":0.047407,"tone_id":"sadness","tone_name":"Sadness"}],"category_id":"emotion_tone","category_name":"Emotion Tone"},{"tones":[{"score":0,"tone_id":"analytical","tone_name":"Analytical"},{"score":0,"tone_id":"confident","tone_name":"Confident"},{"score":0,"tone_id":"tentative","tone_name":"Tentative"}],"category_id":"language_tone","category_name":"Language Tone"},{"tones":[{"score":0.56772,"tone_id":"openness_big5","tone_name":"Openness"},{"score":0.316341,"tone_id":"conscientiousness_big5","tone_name":"Conscientiousness"},{"score":0.425373,"tone_id":"extraversion_big5","tone_name":"Extraversion"},{"score":0.467235,"tone_id":"agreeableness_big5","tone_name":"Agreeableness"},{"score":0.311545,"tone_id":"emotional_range_big5","tone_name":"Emotional Range"}],"category_id":"social_tone","category_name":"Social Tone"}]},
    "transcript_text": "All that glitters isn't gold",
    "transcript_tone": {"tone_categories":[{"tones":[{"score":0.328683,"tone_id":"anger","tone_name":"Anger"},{"score":0.160157,"tone_id":"disgust","tone_name":"Disgust"},{"score":0.285003,"tone_id":"fear","tone_name":"Fear"},{"score":0.062344,"tone_id":"joy","tone_name":"Joy"},{"score":0.047407,"tone_id":"sadness","tone_name":"Sadness"}],"category_id":"emotion_tone","category_name":"Emotion Tone"},{"tones":[{"score":0,"tone_id":"analytical","tone_name":"Analytical"},{"score":0,"tone_id":"confident","tone_name":"Confident"},{"score":0,"tone_id":"tentative","tone_name":"Tentative"}],"category_id":"language_tone","category_name":"Language Tone"},{"tones":[{"score":0.56772,"tone_id":"openness_big5","tone_name":"Openness"},{"score":0.316341,"tone_id":"conscientiousness_big5","tone_name":"Conscientiousness"},{"score":0.425373,"tone_id":"extraversion_big5","tone_name":"Extraversion"},{"score":0.467235,"tone_id":"agreeableness_big5","tone_name":"Agreeableness"},{"score":0.311545,"tone_id":"emotional_range_big5","tone_name":"Emotional Range"}],"category_id":"social_tone","category_name":"Social Tone"}]}
  },
  { "script_text": "Now is the winter of our discontent",
    "script_tone": {"tone_categories":[{"tones":[{"score":0.328683,"tone_id":"anger","tone_name":"Anger"},{"score":0.160157,"tone_id":"disgust","tone_name":"Disgust"},{"score":0.285003,"tone_id":"fear","tone_name":"Fear"},{"score":0.062344,"tone_id":"joy","tone_name":"Joy"},{"score":0.047407,"tone_id":"sadness","tone_name":"Sadness"}],"category_id":"emotion_tone","category_name":"Emotion Tone"},{"tones":[{"score":0,"tone_id":"analytical","tone_name":"Analytical"},{"score":0,"tone_id":"confident","tone_name":"Confident"},{"score":0,"tone_id":"tentative","tone_name":"Tentative"}],"category_id":"language_tone","category_name":"Language Tone"},{"tones":[{"score":0.56772,"tone_id":"openness_big5","tone_name":"Openness"},{"score":0.316341,"tone_id":"conscientiousness_big5","tone_name":"Conscientiousness"},{"score":0.425373,"tone_id":"extraversion_big5","tone_name":"Extraversion"},{"score":0.467235,"tone_id":"agreeableness_big5","tone_name":"Agreeableness"},{"score":0.311545,"tone_id":"emotional_range_big5","tone_name":"Emotional Range"}],"category_id":"social_tone","category_name":"Social Tone"}]},
    "transcript_text": "All that glitters isn't gold",
    "transcript_tone": {"tone_categories":[{"tones":[{"score":0.328683,"tone_id":"anger","tone_name":"Anger"},{"score":0.160157,"tone_id":"disgust","tone_name":"Disgust"},{"score":0.285003,"tone_id":"fear","tone_name":"Fear"},{"score":0.062344,"tone_id":"joy","tone_name":"Joy"},{"score":0.047407,"tone_id":"sadness","tone_name":"Sadness"}],"category_id":"emotion_tone","category_name":"Emotion Tone"},{"tones":[{"score":0,"tone_id":"analytical","tone_name":"Analytical"},{"score":0,"tone_id":"confident","tone_name":"Confident"},{"score":0,"tone_id":"tentative","tone_name":"Tentative"}],"category_id":"language_tone","category_name":"Language Tone"},{"tones":[{"score":0.56772,"tone_id":"openness_big5","tone_name":"Openness"},{"score":0.316341,"tone_id":"conscientiousness_big5","tone_name":"Conscientiousness"},{"score":0.425373,"tone_id":"extraversion_big5","tone_name":"Extraversion"},{"score":0.467235,"tone_id":"agreeableness_big5","tone_name":"Agreeableness"},{"score":0.311545,"tone_id":"emotional_range_big5","tone_name":"Emotional Range"}],"category_id":"social_tone","category_name":"Social Tone"}]}
  },
  { "script_text": "Is this a dagger which I see before me",
    "script_tone": {"tone_categories":[{"tones":[{"score":0.328683,"tone_id":"anger","tone_name":"Anger"},{"score":0.160157,"tone_id":"disgust","tone_name":"Disgust"},{"score":0.285003,"tone_id":"fear","tone_name":"Fear"},{"score":0.062344,"tone_id":"joy","tone_name":"Joy"},{"score":0.047407,"tone_id":"sadness","tone_name":"Sadness"}],"category_id":"emotion_tone","category_name":"Emotion Tone"},{"tones":[{"score":0,"tone_id":"analytical","tone_name":"Analytical"},{"score":0,"tone_id":"confident","tone_name":"Confident"},{"score":0,"tone_id":"tentative","tone_name":"Tentative"}],"category_id":"language_tone","category_name":"Language Tone"},{"tones":[{"score":0.56772,"tone_id":"openness_big5","tone_name":"Openness"},{"score":0.316341,"tone_id":"conscientiousness_big5","tone_name":"Conscientiousness"},{"score":0.425373,"tone_id":"extraversion_big5","tone_name":"Extraversion"},{"score":0.467235,"tone_id":"agreeableness_big5","tone_name":"Agreeableness"},{"score":0.311545,"tone_id":"emotional_range_big5","tone_name":"Emotional Range"}],"category_id":"social_tone","category_name":"Social Tone"}]},
    "transcript_text": "All that glitters isn't gold",
    "transcript_tone": {"tone_categories":[{"tones":[{"score":0.328683,"tone_id":"anger","tone_name":"Anger"},{"score":0.160157,"tone_id":"disgust","tone_name":"Disgust"},{"score":0.285003,"tone_id":"fear","tone_name":"Fear"},{"score":0.062344,"tone_id":"joy","tone_name":"Joy"},{"score":0.047407,"tone_id":"sadness","tone_name":"Sadness"}],"category_id":"emotion_tone","category_name":"Emotion Tone"},{"tones":[{"score":0,"tone_id":"analytical","tone_name":"Analytical"},{"score":0,"tone_id":"confident","tone_name":"Confident"},{"score":0,"tone_id":"tentative","tone_name":"Tentative"}],"category_id":"language_tone","category_name":"Language Tone"},{"tones":[{"score":0.56772,"tone_id":"openness_big5","tone_name":"Openness"},{"score":0.316341,"tone_id":"conscientiousness_big5","tone_name":"Conscientiousness"},{"score":0.425373,"tone_id":"extraversion_big5","tone_name":"Extraversion"},{"score":0.467235,"tone_id":"agreeableness_big5","tone_name":"Agreeableness"},{"score":0.311545,"tone_id":"emotional_range_big5","tone_name":"Emotional Range"}],"category_id":"social_tone","category_name":"Social Tone"}]}
  }
];